(define (problem merry)
  (:domain merry)
  (:objects
  	 zielony czerwony pomaranczowy rozowy niebieski - color
     a b c d e f g h i - room
     az br cp cn dz dc en ez fn1 fn2 hz hc ip in - ball
     merry - pivot
  )
  (:init
    (color az zielony)
    (ballInRoom az a)
    (color br rozowy)
    (ballInRoom br b)
    (color cp pomaranczowy)
    (ballInRoom cp c)
    (color cn niebieski)
    (ballInRoom cn c)
    (color dz zielony)
    (ballInRoom dz d)
    (color dc czerwony)
    (ballInRoom dc d)
    (color en niebieski)
    (ballInRoom en e)
    (color ez zielony)
    (ballInRoom ez e)
    (color fn1 niebieski)
    (ballInRoom fn1 f)
    (color fn2 niebieski)
    (ballInRoom fn2 f)
    (color hz zielony)
    (ballInRoom hz h)
    (color hc czerwony)
    (ballInRoom hc h)
    (color ip pomaranczowy)
    (ballInRoom ip i)
    (color in niebieski)
    (ballInRoom in i)

    (door a b pomaranczowy)
    (door a c czerwony)
    (door c a czerwony)
    (door b d pomaranczowy)
    (door c e zielony)
    (door e c zielony)
    (door d f zielony)
    (door f d zielony)
    (door e f niebieski)
    (door f e niebieski)
    (door e h czerwony)
    (door h e czerwony)
    (door f i niebieski)
    (door i f niebieski)
    (door h i niebieski)
    (door i h niebieski)
    (door f g rozowy)

    (merry f)
  )
  (:goal

    (merry g)
  )
)
